version: '3.4'
services:
  web:
    build:
      context: .
      target: dev_builder
    command:
      - "/bin/sh"
      - -ecx
      - |
        echo 'Compiling prom-aggregation-gateway!'
        CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o bin/app ./cmd/prom-aggregation-gateway
        echo 'Starting prom-aggregation-gateway'
        ./bin/app --listen=:8080 --time-to-live-ms=10000
    ports:
      - '1234:8080'
    volumes:
      - .:/go/src/github.com/adharmonics/prom-aggregation-gateway
